# Generated by Django 4.1.7 on 2023-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="studentstatus",
            field=models.CharField(default="INTERN", max_length=20),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="tutortoken",
            field=models.CharField(
                blank=True, default="nothing", max_length=50, null=True
            ),
        ),
    ]
