# Generated by Django 4.1.4 on 2023-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_Tutor',
            field=models.BooleanField(default=False),
        ),
    ]
