# Generated by Django 4.1.5 on 2023-03-14 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_courses_course_description_and_more'),
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='ml_model',
            field=models.FileField(blank=True, null=True, upload_to='mlmodels/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['onnx'])]),
        ),
        migrations.CreateModel(
            name='RankingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('model_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.mlmodel')),
                ('used_metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='challenges.metric')),
            ],
        ),
    ]
