# Generated by Django 4.1.5 on 2023-03-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_alter_mlmodel_ml_model_rankingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='rankingmodel',
            name='metric_score',
        ),
        migrations.RemoveField(
            model_name='rankingmodel',
            name='model_ref',
        ),
        migrations.RemoveField(
            model_name='rankingmodel',
            name='used_metric',
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='challenge_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='model_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_human', models.BooleanField(default=False)),
                ('metric_eval', models.ManyToManyField(to='ranking.metriceval')),
            ],
        ),
    ]
