# Generated by Django 4.1.3 on 2023-03-15 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_remove_rankingentry_metric_eval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='ml_model',
            field=models.FileField(upload_to='mlmodels/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['onnx'])]),
        ),
    ]
