# Generated by Django 4.1.7 on 2023-03-16 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0005_alter_mlmodel_ml_model"),
    ]

    operations = [
        migrations.RemoveField(model_name="rankingentry", name="metric_name",),
        migrations.RemoveField(model_name="rankingentry", name="metric_value",),
        migrations.AddField(
            model_name="rankingentry",
            name="Accuracy",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="rankingentry",
            name="Challengid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rankingentry",
            name="F1",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="rankingentry",
            name="Precision",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="rankingentry",
            name="Recall",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="rankingentry",
            name="model_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ranking.mlmodel",
            ),
        ),
        migrations.AddField(
            model_name="rankingentry",
            name="modelname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
