# Generated by Django 4.1.5 on 2023-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=500)),
                ('title_text', models.CharField(max_length=50)),
                ('dataset_url', models.URLField()),
                ('metric_choice', models.TextField(choices=[('1', 'accuracy'), ('2', 'precision'), ('3', 'recall')])),
            ],
        ),
    ]
