# Generated by Django 4.1.5 on 2023-03-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_formular', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='metric_choice',
        ),
        migrations.AddField(
            model_name='challenge',
            name='metric_choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Metrics', to='challenges.metric'),
        ),
    ]
