# Generated by Django 4.1.5 on 2023-03-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_rolls_remove_challenge_metric_choices_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rolls',
            new_name='Roles',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='roll_name',
            new_name='role_name',
        ),
        migrations.AddField(
            model_name='challenge',
            name='role_choices',
            field=models.ManyToManyField(to='challenges.roles'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='metric_choices',
            field=models.ManyToManyField(to='challenges.metric'),
        ),
    ]
