# Generated by Django 4.1.5 on 2023-03-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_rename_rolls_roles_rename_roll_name_roles_role_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='remaining_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
