# Generated by Django 4.1.5 on 2023-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_remaining_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='remaining_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
