# Generated by Django 4.1.4 on 2023-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_courses_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_human',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='min_classification',
            field=models.IntegerField(null=True),
        ),
    ]
