# Generated by Django 4.1.4 on 2023-03-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_challenge_is_human_challenge_min_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='max_classification',
            field=models.IntegerField(null=True),
        ),
    ]
